language: go
dist: focal
go:
  - 1.16

before_script:
  - sudo apt -y install ninja-build
addons:
  apt:
    update: true

script:
  - cd ./build
  - go build ./cmd/bood/main.go
  - ./main
  - cd ../example && ../build/out/bin/bood
